services:
  db1:
    image: mysql:8.4.3
    container_name: book-rapid-jpa-msa-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${LOCAL_DEVDB_SUPER_PASSWORD}
      LANG: C.UTF-8
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
      - --default-time-zone=Asia/Seoul
    volumes:
      - book-rapid-jpa-msa-db1-data:/var/lib/mysql
    restart: always
  db2:
    image: postgres:17.2-bookworm
    container_name: book-rapid-jpa-msa-postgres
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${LOCAL_DEVDB_SUPER_PASSWORD}
      LANG: C.UTF-8
      TZ: Asia/Seoul
    volumes:
      - book-rapid-jpa-msa-db2-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
volumes:
  book-rapid-jpa-msa-db1-data:
  book-rapid-jpa-msa-db2-data: