services:
  db1:
    image: mysql:8.4.3
    container_name: book-rapid-jpa-msa-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${LOCAL_DEVDB_SUPER_PASSWORD}
      LANG: C.UTF-8
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
      - --default-time-zone=Asia/Seoul
    volumes:
      - book-rapid-jpa-msa-db1-data:/var/lib/mysql
    restart: always
  db2:
    image: postgres:17.2-bookworm
    container_name: book-rapid-jpa-msa-postgres
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${LOCAL_DEVDB_SUPER_PASSWORD}
      LANG: C.UTF-8
      TZ: Asia/Seoul
    volumes:
      - book-rapid-jpa-msa-db2-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - book-rapid-jpa-msa-mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8091:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  zipkin:
    image: openzipkin/zipkin-slim
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to increase heap size
      # - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    # Uncomment to enable debug logging
    # command: --logging.level.zipkin2=DEBUG
volumes:
  book-rapid-jpa-msa-db1-data:
  book-rapid-jpa-msa-db2-data:
  book-rapid-jpa-msa-mongo-data: